version: "3.9"
services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: insta
      POSTGRES_PASSWORD: insta
      POSTGRES_DB: insta
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  content:
    build:
      context: .
      dockerfile: services/content/Dockerfile
    depends_on:
      - postgres
    environment:
      # перетираем grpc.addr на :9082
      CONTENT_GRPC_ADDR: ":9082"
      # перетираем postgres.dsn (важно именно CONTENT_POSTGRES_DSN)
      CONTENT_POSTGRES_DSN: "postgres://insta:insta@postgres:5432/insta?sslmode=disable"
      CONTENT_STORAGE_UPLOAD_DIR: "/data"
    volumes:
      - ./data:/data
    ports:
      - "9082:9082"

volumes:
  pgdata:
